library(bcbioRNASeq)
uuo <- loadRNASeq("~/orch/hbc/PIs/vishal_vaidya/vishal_mirna_kidney/scientific_data/uuo/mrna/mrna/final", interestingGroups = "group")
saveData(uuo, dir = "../data")
fa <- loadRNASeq("~/orch/hbc/PIs/vishal_vaidya/vishal_mirna_kidney/scientific_data/fa/mrna/mrna/final", interestingGroups = "group")
saveData(fa, dir = "../data")
library(bcbioSmallRna)
suuo <- loadSmallRnaRun("~/orch/hbc/PIs/vishal_vaidya/vishal_mirna_kidney/scientific_data/uuo/mirna/mirna/final", interestingGroups = "time")
saveData(suuo, dir = "../data")
sfa <- loadSmallRnaRun("~/orch/hbc/PIs/vishal_vaidya/vishal_mirna_kidney/scientific_data/fa/mirna/mirna/final", interestingGroups = "group")
saveData(sfa, dir = "../data")
